on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'
        system-packages: 'guile-devel zlib-devel gettext portaudio-devel portmidi-devel libsndfile-devel autogen libdb-devel wget'
        pre-build-command: 'sh manylinux-pre-build-script.sh'
        pip-wheel-args: '-w ./dist --build-option --use-double --build-option --use-jack'
    - name: Publish wheels to test PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository testpypi dist/*-manylinux*.whl
